### ISSUE TITLE
Failed to run "python setup.py build_ext --inplace"

### ISSUE THREAD

**Issue by TixiaoShan** [valeoai/POCO#1]
Hello,

After installing Pytorch and Pytorch Geometric, running `python setup.py build_ext --inplace` gives the following error:

```
gcc: error: /my/computer/path/to/POCO/build/temp.linux-x86_64-3.7/eval/src/utils/libkdtree/pykdtree/_kdtree_core.o: No such file or directory
error: command 'gcc' failed with exit status 1
```

Any suggestions would be appreciated.

**Comment by TixiaoShan** [comment]
[Using the Cython version specified in the file solved the problem.](https://github.com/valeoai/POCO/blob/17e3b352da592bd888c1b69567552107fffa1553/eval/src/utils/libkdtree/pykdtree/kdtree.c#L1)

**Comment by aboulch** [comment]
Thanks for for the note.
