### ISSUE TITLE
unable to run code 

### ISSUE THREAD

**Issue by cyberkarim** [valeoai/POCO#17]
Hello,

I'm running into an issue after setting up my poco environement using the specified requirements. 
My gpu specs :
![hap2](https://github.com/valeoai/POCO/assets/58376217/d31e52dd-3c1a-4986-9a9f-66731edeaa97)

I'm unable to run the first : python train.py --config configs/config_shapenet.yaml 

The actual error
![hap1](https://github.com/valeoai/POCO/assets/58376217/16f85dc2-fb39-427a-89e2-7d23b61e74e9)

**Comment by aboulch** [comment]
This is the same issue as #6 .
I am investigating the possible problems.
Difficulties come from the fact as it runs well on my machine.

**Comment by aboulch** [comment]
Dupplicate of #6
