### ISSUE TITLE
Training on my own dataset

### ISSUE THREAD

**Issue by Green89757** [valeoai/POCO#5]
I met some problem when training on my own dataset, which is processed as ShapeNet, containing **pointclouds with normals, SDF points and occ values**.  However, there is an error when I try to train on it.

`  File "/media/yangxilab/DiskB/sanren/3Drecon/POCOnasa/networks/backbone/fkaconv_network.py", line 193, in forward
    x0 = self.activation(self.bn0(self.cv0(x, pos, pos, data["ids00"])))
KeyError: 'ids00'`

I'm confusing that what `data["ids00"]` in `x0 = self.activation(self.bn0(self.cv0(x, pos, pos, data["ids00"])))` refers to? And similarily, there are many unkown data like `data["ids10"]`. How could I get this data? Thanks in advance!

**Comment by ListIndexOutOfRange** [comment]
It looks like these values should be computed inside the forward_spatial method of fkaconv_network (https://github.com/valeoai/POCO/blob/main/networks/backbone/fkaconv_network.py#L92). 
Perhaps you setted  spectral_only to True wheras it should have been False ?

**Comment by Hxinyue** [comment]
https://github.com/valeoai/POCO/issues/5#issue-1242876672
Hello, I have my own point cloud data file in. ply format. How can I handle it for training? We look forward to your reply！
