### ISSUE TITLE
Download ABC / RealWorld / Famous and Thingi10k data

### ISSUE THREAD

**Issue by MulinYu** [valeoai/POCO#9]
Hello,

Thanks for the excellent paper and for releasing the code.

I'm wondering where I can download the ABC, RealWorld, Famous, and Thingi10k data?

Best and have a nice day,
Mulin

**Comment by aboulch** [comment]
Hello,

To download these datasets, please refer to Points2Surf repository here:
https://github.com/ErlerPhilipp/points2surf

Best,

**Comment by MulinYu** [comment]
Thanks alot.

**Comment by hyzhou404** [comment]
> Hello,
> 
> To download these datasets, please refer to Points2Surf repository here: https://github.com/ErlerPhilipp/points2surf
> 
> Best,

Points2surf uses SDF representation while POCO uses occupancy representation. Can the datasets generated for points2surf directly apply on POCO?

**Comment by aboulch** [comment]
Hello,
Yes, SDF values are thresholded: `occupancy = (SDF < 0)`.
Best,
